### ISSUE TITLE
IPv6 and radar.cloudflare.com

### ISSUE THREAD

**Issue by cipnt** [jeroenvdw/hassio-cloudflare-update#2]
This is great! Just installed it and had it up and running in a minute. Great stuff!
I particularly love how simple [the code](https://github.com/jeroenvdw/hassio-cloudflare-update/blob/9a2f4bcb8f52e0ea5734dafc56eb2daf4f0b5372/cloudflare_dns_update/update_dns_record.py) is and easy to verify.

A couple suggestions from me:
- use [Cloudflare’s own IP tool](https://ipv4-check-perf.radar.cloudflare.com/api/info) instead of [api.ipify.org](http://api.ipify.org/)
- extend this to [IPv6](https://ipv6-check-perf.radar.cloudflare.com/api/info) too since a lot of us are now behind CG-NAT
- increase the default `sleep_time` to not overwhelm these APIs/servers

Thanks!

**Comment by jeroenvdw** [comment]
Hi,

Thanks for the suggestions!

However I do like ipify, because it is so simple to use. They are also 100% open source, and promise not to track their users.
Also, they state that anyone can use their service freely, even for millions of requests per minute. So I believe the default sleep time of 5 minutes is ok ;-) 

For IPv6, it would be nice indeed to support it. I see that ipify has a service (https://api64.ipify.org) that could retrieve either an IPv4 or IPv6 address. I guess updating the AAAA record for IPv6 addresses would do the trick? Since I don't have an IPv6 address myself, it would be very hard to test though.

If you would be able to test IPv6, I'd be happy to try to add support for it.

Best regards,
Jeroen

**Comment by cipnt** [comment]
> They are also 100% open source, and promise not to track their users.
> Also, they state that anyone can use their service freely

I din't know that. I'm always skeptical of free services – they either close without warning or they begin charging once they get popular enough. 
The reason I thought Cloudflare's IP API would be more suitable here is because this is a Clouflare add-on after all. If one is down, the other will most likely be down to0. Unlikely, but it has happened. 


> I see that ipify has a service (https://api64.ipify.org) that could retrieve either an IPv4 or IPv6 address.

The annoying thing about https://api64.ipify.org is that it will return an IPv4 if it can't get the IPv6, so extra logic and checks are required.
While https://ipv6-check-perf.radar.cloudflare.com/api/info  does not resolve for an IPv4-only client (i.e it only has an AAAA record)

> I guess updating the AAAA record for IPv6 addresses would do the trick?

Indeed. If the add-on can detect a public IPv6 and if there is an AAAA record for the target domain/subdomain, then it should update it.

> If you would be able to test IPv6, I'd be happy to try to add support for it.

Definitely happy to test an IPv6 option. 
I'm on an IPv6-only ISP which shares an IPv4 with multiple customers (CG-NAT), which I understand is becoming more common now with the limited supply of IPv4 addresses.
For this kind of internet connection it would actually benefit from an IPv6-only mode. I guess this could be achieved either with an option in the add-on or by creating only an AAAA record in Cloudflare for the desired subdomain.

**Comment by jeroenvdw** [comment]
Hi @cipnt 
I created a new version, to support IPv6. Can you test and give me feedback?

**Comment by cipnt** [comment]
After updating the add-on and enabling IPv6, it has successfully updated the A record but failed on the AAAA:

``
ERROR: Failed to get public IP - Are you sure you are on IPv6? [Errno -2] Name does not resolve
Exiting - error: [Errno -2] Name does not resolve
``

I think there is a typo in your code 
`
if IPv6Mode:
        conn = http.client.HTTPSConnection("ap6.ipify.org")
`

This [doesn't resolve](https://toolbox.googleapps.com/apps/dig/#AAAA/ap6.ipify.org) at all. Shouldn't it be [api64.ipify.org](https://toolbox.googleapps.com/apps/dig/#AAAA/api64.ipify.org) ?

**Comment by jeroenvdw** [comment]
No, https://api6.ipify.org is correct, but it does only resolve when you have an actual IPv6 address. The address https://api64.ipify.org returns an IPv4 or IPv6. But when both are available, it returns an IPv4. (tried it with a VPN)

Can you check (ideally on the machine you are running Home Assistant on, or at least on the same home network as that machine) if you actually have an IPv6 address? You can easily check by browsing for example to https://whatismyipaddress.com/ , it will give you both IPv4 and IPv6 if they are both available. And in that case, https://api6.ipify.org should resolve as well.

**Comment by cipnt** [comment]
Your code has "`ap6.ipify.org`" instead of "`api64.ipify.org`" or "`api6.ipify.org`". 
I think the typo is on [line 25](https://github.com/jeroenvdw/hassio-cloudflare-update/blob/d729c17b829c92f37ca657ccf6cbd54b8ce8227e/cloudflare_dns_update/update_dns_record.py#L25)...

From my Home Assistant machine:
```
~ curl http://ap6.ipify.org
curl: (6) Could not resolve host: ap6.ipify.org

~ curl http://api64.ipify.org             
2a0e:cb01:60:b800:*:*:*:*#   

curl http://api6.ipify.org                    
2a0e:cb01:60:b800:*:*:*:*# 

~ curl http://api.ipify.org               
145.40.128.*#  
```

**Comment by jeroenvdw** [comment]
Oops... indeed, I missed the typo. It's corrected now.
Can you update once again, test, and let me know?
Thanks!

**Comment by cipnt** [comment]
When selecting both IPv4 and IPv6 I get no errors but only the A record gets updated:
```
INFO: Retrieving DNS records from Cloudlare
{'result': *
INFO: Updating DNS record
{'result': {'id': '6fea86b507dec15aa6cb89e910bbee82'}, 'success': True, 'errors': [], 'messages': []}
INFO: Retrieving DNS records from Cloudlare
```
Presumably the second request to Cloudflare is for the AAAA record but there is nothing after that. No errors and the add-on is still showing as running.


When I enable just IPv6 I get the following error in the logs:
```
Traceback (most recent call last):
  File "/update_dns_record.py", line 96, in <module>
    update_DNS_Record_IP(DNS_record_ID, public_IPv4,IPv6Mode=True)
                                        ^^^^^^^^^^^
NameError: name 'public_IPv4' is not defined. Did you mean: 'public_IPv6'?
```

The logs show that it is successfully retrieving DNS records from Cloudlare with all records on my domain including the AAAA record that it is meant to be updated.

**Comment by jeroenvdw** [comment]
Ah I see, it was trying to update with the IPv4-variable. Which is not filled in case of IPv6 only.
Did an update, can you try once more?

**Comment by cipnt** [comment]
Works great! At least the initial setup.
The A and AAAA records are updated when both IPv4 and IPv6 are enabled as well as when just one is enabled.

However, I don't believe the loop with the sleep timer is working as expected.
I changed the timer to a lower value but there are no further checks or updates to the DNS when IPv6 is enabled.
After the add-on starts and it initially updates the A and AAAA records correctly, if I manually change the value of these in Cloudflare, then this is not picked up or updated by the add-on when IPv6 is enabled.

Also, the code has a few `print` functions which should make it quite verbose in the logs, but there isn't anything else in the logs after the initial setup when IPv6 is enabled.
When only IPv4 is enabled I see in the logs the repeated `INFO: Publc IPv4 address has not changed!` which suggests iti is going through the `while` loop.

**Comment by jeroenvdw** [comment]
Happy to hear that it works! 

On the update loop: I keep track in the code of the IP-address, and only when it changes, I collect the A / AAAA record to see if needs to be updated. 
So updating the A / AAAA manually in Cloudflare won't trigger an update with this addon.
